name: gitcoin
description: A Cryptocurrency to support Open Source Contributors
version: 0.0.1
authors:
  - Konstantin Ullrich <konstantinullrich12@gmail.com>
  - Andreas Döring <andreas.doering@tum.de>
  - Houssein Zaghdane <ge72xim@mytum.de>
  - Moritz Wolf <moritz@moritz-wolf.de>
# homepage: https://www.example.com

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  crypto: ^2.1.3
  pointycastle: ^1.0.2
  asn1lib: ^0.5.14
  http: ^0.12.0+2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
